### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by alexisrolland** [TaoK/poor-mans-t-sql-formatter-vscode-extension#6]
Hello,
I have installed the plugin in VS Studio Code but I have not seen any documentation explaining how to use / how to apply the formatting on the current file.
Thank you in advance for your help.
Alexis

**Comment by jwhart91** [comment]
also curious

**Comment by mvarendorff** [comment]
From #1 Shortcut is Ctrl+K Shift+F. PR #4 introduces the default formatter keybinding but isn't merged yet.
